CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `agenda`.`contato` (
	`codigo` INT(11) NOT NULL AUTO_INCREMENT,
	`nome` VARCHAR(150) NOT NULL,
	`telefone` VARCHAR(150) NOT NULL,
	`email` VARCHAR(150) NOT NULL,
	`endereco` VARCHAR(255) NOT NULL,
	`idade` INT(11) NOT NULL,
	`linkedin` VARCHAR(255) NOT NULL,

  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;